# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kernel <- function(x1, x2, b) {
    .Call('_gpss_kernel', PACKAGE = 'gpss', x1, x2, b)
}

kernel_symmetric <- function(x, b) {
    .Call('_gpss_kernel_symmetric', PACKAGE = 'gpss', x, b)
}

kernel_linear_cpp <- function(x1, x2, sigma_f) {
    .Call('_gpss_kernel_linear_cpp', PACKAGE = 'gpss', x1, x2, sigma_f)
}

kernel_se_cpp <- function(x1, x2, sigma_f, l) {
    .Call('_gpss_kernel_se_cpp', PACKAGE = 'gpss', x1, x2, sigma_f, l)
}

kernel_periodic_cpp <- function(x1, x2, sigma_f, l, p) {
    .Call('_gpss_kernel_periodic_cpp', PACKAGE = 'gpss', x1, x2, sigma_f, l, p)
}

log_marginal_likelihood_cpp <- function(K, y, s2) {
    .Call('_gpss_log_marginal_likelihood_cpp', PACKAGE = 'gpss', K, y, s2)
}

